export const webhookFields = [
    { name: 'orderId' },
    { name: 'id' },
    { name: 'privateId' },
    { name: 'shopOrderId' },
    { name: 'channel' },
    { name: 'ecomShopId' },
    { name: 'saleChannel' },
    { name: 'merchantTrackingNumber' },
    { name: 'depotId' },
    { name: 'handoverId' },
    { name: 'depotName' },
    { name: 'type' },
    { name: 'typeId' },
    { name: 'moneyDiscount' },
    { name: 'moneyDeposit' },
    { name: 'moneyTransfer' },
    { name: 'creditAmount' },
    { name: 'depositAccount' },
    { name: 'transferAccount' },
    { name: 'creditAccount' },
    { name: 'usedPoints' },
    { name: 'moneyUsedPoints' },
    { name: 'usedPointAmount' },
    { name: 'carrierId' },
    { name: 'carrierName' },
    { name: 'serviceId' },
    { name: 'serviceName' },
    { name: 'carrierServiceType' },
    { name: 'carrierServiceTypeName' },
    { name: 'carrierCode' },
    { name: 'shipFee' },
    { name: 'customerShipFee' },
    { name: 'returnFee' },
    { name: 'overWeightShipFee' },
    { name: 'declaredFee' },
    { name: 'description' },
    { name: 'privateDescription' },
    { name: 'customerId' },
    { name: 'customerName' },
    { name: 'customerEmail' },
    { name: 'customerMobile' },
    { name: 'customerAddress' },
    { name: 'shipToCityLocationId' },
    { name: 'shipToDistrictLocationId' },
    { name: 'shipToWardLocationId' },
    { name: 'customerCity' },
    { name: 'customerDistrict' },
    { name: 'customerWard' },
    { name: 'createdById' },
    { name: 'createdByUserName' },
    { name: 'createdByName' },
    { name: 'saleId' },
    { name: 'saleName' },
    { name: 'createdDateTime' },
    { name: 'deliveryDate' },
    { name: 'sendCarrierDate' },
    { name: 'statusName' },
    { name: 'statusCode' },
    { name: 'calcTotalMoney' },
    { name: 'trafficSourceId' },
    { name: 'trafficSourceName' },
    { name: 'affiliateCode' },
    { name: 'affiliateBonusCash' },
    { name: 'affiliateBonusPercent' },
    { name: 'tags' },
    { name: 'couponCode' },
    { name: 'returnFromOrderId' },
    { name: 'utmSource' },
    { name: 'utmMedium' },
    { name: 'utmCampaign' },
    { name: 'facebook' },
    { name: 'updatedAt' },
    { name: 'packed' },
    { name: 'codFee' },
    { name: 'status' },
    { name: 'statusDescription' },
    { name: 'trackingUrl' },
    { name: 'reason' },
    {
        name: 'products',
        type: 'array',
        subFields: [
            { name: 'productId', type: 'string' },
            { name: 'productName', type: 'string' },
            { name: 'productCode', type: 'string' },
            { name: 'productBarcode', type: 'string' },
            { name: 'productImage', type: 'string' },
            { name: 'price', type: 'float' },
            { name: 'quantity', type: 'int' },
            { name: 'weight', type: 'float' },
            { name: 'vat', type: 'float' },
            { name: 'discount', type: 'float' },
            { name: 'description', type: 'string' },
            { name: 'imei', type: 'string' },
            { name: 'giftProducts', type: 'string' },
            { name: 'batch', type: 'string' },
            { name: 'comboItems', type: 'string' },
            { name: 'productMoney', type: 'string' },
            { name: 'priceOriginal', type: 'string' },
            { name: 'avgCost', type: 'string' },
        ],
    },
    { name: "customer_id" },
    { name: "customer_type" },
    { name: "customer_name" },
    { name: "customer_mobile" },
    { name: "customer_gender" },
    { name: "customer_email" },
    { name: "customer_address" },
    { name: "customer_birthday" },
    { name: "customer_code" },
    { name: "customer_level" },
    { name: "customer_group" },
    { name: "customer_levelId" },
    { name: "customer_groupId" },
    { name: "customer_cityLocationId" },
    { name: "customer_districtLocationId" },
    { name: "customer_wardLocationId" },
    { name: "customer_totalMoney" },
    { name: "customer_startedDate" },
    { name: "customer_startedDepotId" },
    { name: "customer_points" },
    { name: "customer_totalBills" },
    { name: "customer_lastBoughtDate" },
    { name: "customer_taxCode" },
    { name: "customer_businessName" },
    { name: "customer_businessAddress" },
    { name: "customer_description" },
];
