export const webhookFields = [
    'orderId',
    'shopOrderId',
    'saleChannel',
    'type',
    'typeId',
    'moneyDiscount',
    'moneyDeposit',
    'moneyTransfer',
    'creditAmount',
    'usedPoints',
    'moneyUsedPoints',
    'shipFee',
    'codFee',
    'customerShipFee',
    'calcTotalMoney',
    'description',
    'customerId',
    'customerName',
    'customerEmail',
    'customerMobile',
    'customerAddress',
    'shipToCityLocationId',
    'shipToDistrictLocationId',
    'shipToWardLocationId',
    'customerCity',
    'customerDistrict',
    'customerWard',
    'createdById',
    'couponCode',
    'status',
    'statusDescription',
    'depotId',
    'trackingUrl',
    'createdDateTime',
    'reason',
    'deliveryDate',
    {
        name: 'products',
        type: 'array',
        subFields: [
            { name: 'id', type: 'string' },
            { name: 'quantity', type: 'int' },
            { name: 'price', type: 'float' },
            { name: 'discount', type: 'float' },
            { name: 'weight', type: 'float' },
        ],
    },
];